"use client";

import { ThemeProvider } from "styled-components";
import { LifeSGTheme } from "@lifesg/react-design-system/theme";
import { useEffect, useState, type ReactNode } from "react";

/**
 * Wraps the LifeSG reference panes. Renders client-only.
 *
 * Why: LifeSG ships pre-bundled to node_modules. Next's SWC
 * `compiler.styledComponents: true` transform doesn't reach vendored code, so
 * the `componentId` hashes generated by `styled.button` / `styled.ul` etc.
 * differ between the SSR bundle (Node) and CSR bundle (browser). Result: a
 * React-19 hydration mismatch warning on every page that renders a LifeSG
 * styled-component. Gating client-only sidesteps the SSR step entirely for the
 * reference pane — brief blank flash on first paint, no console noise.
 */
export function LifeSGProvider({ children }: { children: ReactNode }) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;
  return <ThemeProvider theme={LifeSGTheme.light}>{children}</ThemeProvider>;
}
